### PR TITLE
Tweak: Left justify batter and pitcher names if they are short enough to avoid scrolling

### PR DESCRIPTION
**Pull request by WardBrian**
We could make this a config in the layout if we wanted, for now I'm assuming it is better default behavior.

Comparison (specifically noticeable for short batter names like Soto):

Before:
before

After:
after

### CODE REVIEW

**Comment by WardBrian** [comment]
@ty-porter was this closed on purpose or as a side effect of the release process?

**Comment by ty-porter** [comment]
Sorry about that, it was closed during release when I spun up a new dev branch and killed off the old one.

**Comment by WardBrian** [comment]
@twfarley this PR now hides the scores on the pregame in addition to justifying the pitcher/batter

**Comment by twfarley** [comment]
looks good to me. thanks, Brian.

**Pull request merged**
