### PR TITLE
Fix preferred team 

### PR DESCRIPTION
**Pull request by tracerrx**
A bugfix to allow for scrolling/selection of second/third preferred team even if first is not playing today.

### CODE REVIEW

**Comment by WardBrian** [comment]
What is the intended behavior here? If your number 1 preferred team isn't playing but a later one is, the first one on that list becomes "sticky" and doesn't rotate?

This is sort of tricky to change because I quite like the way I currently have things. My config is:

Nats as my preferred team
Several other teams I follow listed afterwards

Rotation is set to "only preferred" and enabled only during inning breaks for my preferred team (the Nats).

So, if the Nats are playing, I always see their game. During inning breaks, or if they are not playing, it will rotate through the Red Sox, Mets, etc. (my other preferred teams). 

After this PR, it sounds like rather than rotating through those other teams, it would always prefer to show one of them. Is that correct?

Assuming so, we probably want to split this idea into something like "preferred teams" and "followed teams", with the second referring to teams I want to see in the rotation but never really want to become the "favorite"/sticky game

**Comment by tracerrx** [comment]
Maybe, whats happens now is that if your primary preferred team is off today, none of the other preferred team games show. It only works if your primary preferred team is playing. Set you config to yankees and blue jays, you would expect to see the toronto game but you don't because the yankees game was postponed.

**Comment by WardBrian** [comment]
I think that’s only true if you have one or both of the “team_offday” config settings enabled

**Comment by WardBrian** [comment]
I have it set it to show on league off days only, not team off days. These are pretty rare during the season, mostly things like the All Star Break

**Comment by tracerrx** [comment]
I think what were looking for is a mix.. from your above post I agree it should be: "So, if the Nats are playing, I always see their game. During inning breaks, or if they are not playing, it will rotate through the Red Sox, Mets, etc. (my other preferred teams)." But when there are no games active (i.e. in the morning) it should show weather etc.  Currently it will do that if you have news ticker team offday set to true only, but then it misses your 2nd/3rd team games.

**Comment by WardBrian** [comment]
Yeah, this is why I added the ability for standings to show if no game was currently life (rather than if it was an off day). Something similar for the News/Weather is probably what we want

**Comment by tracerrx** [comment]
So lets close this PR.. and later on well add "display_no_games_live" functionality to both weather and news... I didn't realize that was there for standings...

**Comment by WardBrian** [comment]
If we can make it so weather and news aren’t the select-once-and-stay-there style they currently are, we’re like 70% of the way to letting you pick whatever rotation order you want, which would be sweet. It would be cool to show the standings during the inning breaks, or the weather

**Pull request closed without merging**
