### PR TITLE
Add a default layout for 64x64

### LINKED ISSUE #199: 64x64 support
Add a default layout for 64x64

### PR DESCRIPTION
**Pull request by pawptart**
Closes #199. Adds a default layout for 64x64 LED matrices.

### CODE REVIEW

**Comment by ajbowler** [comment]
@pawptart can you upload a screenshot of what this looks like? Will add it to the README.

**Comment by pawptart** [comment]
Absolutely, I'll get you some screenshots tonight.

**Comment by ajbowler** [comment]
Beautiful. Let's get this out!

**Comment by BillLehecka** [comment]
I just set up 64x32 last night (everything’s postponed... boo...) but I too would like to see what 64x64 looks like.

**Pull request merged**
