### PR TITLE
Merge pull request #194 from MLB-LED-Scoreboard/dev 128-64 support

### PR DESCRIPTION
**Pull request by jasonbogovich**
Release 2.0.0

```
{
  "defaults": {
    "font_name": "9x18B"
  },
  "bases": {
    "1B": {
      "x": 75,
      "y": 43,
      "size": 18
    },
    "2B": {
      "x": 65,
      "y": 33,
      "size": 18
    },
    "3B": {
      "x": 55,
      "y": 43,
      "size": 18
    }
  },
  "final": {
    "inning": {
      "x": 67,
      "y": 61
    },
    "scrolling_text": {
      "x": 0,
      "y": 44,
      "width": 128
    },
    "nohit_text": {
      "x": 1,
      "y": 33
    }
  },
  "inning": {
    "break": {
      "number": {
        "x": 87,
        "y": 44
      },
      "text": {
        "x": 46,
        "y": 44
      }
    },
    "number": {
      "x": 120,
      "y": 45
    },
    "arrow": {
      "size": 8,
      "up": {
        "x_offset": -12,
        "y_offset": -10
      },
      "down": {
        "x_offset": -12,
        "y_offset": -2
      }
    }
  },
  "outs": {
    "1": {
      "x": 2,
      "y": 48,
      "size": 12,
      "nohit": {
        "x": 5,
        "y": 58,
        "size": 8
      },
      "perfect_game": {
        "x": 5,
        "y": 58,
        "size": 8
      }
    },
    "2": {
      "x": 16,
      "y": 48,
      "size": 12,
      "nohit": {
        "x": 19,
        "y": 58,
        "size": 8
      },
      "perfect_game": {
        "x": 18,
        "y": 52,
        "size": 8
      }
    },
    "3": {
      "x": 30,
      "y": 48,
      "size": 12,
      "nohit": {
        "x": 23,
        "y": 58,
        "size": 8
      },
      "perfect_game": {
        "x": 23,
        "y": 55,
        "size": 8
      }
    }
  },
  "batter_count": {
    "x": 2,
    "y": 45,
    "nohit": {
      "x": 32,
      "y": 45
    },
    "perfect_game": {
      "x": 32,
      "y": 45
    }
  },
  "nohitter": {
    "x": 32,
    "y": 45,
    "innings_until_display": 5
  },
  "pregame": {
    "scrolling_text": {
      "x": 0,
      "y": 46,
      "width": 128,
      "warmup": {
        "x": 0,
        "y": 46,
        "width": 128
      }
    },
    "start_time": {
      "x": 66,
      "y": 60
    },
    "warmup_text": {
      "x": 66,
      "y": 60
    }
  },
  "standings": {
    "offset": 12,
    "height": 64,
    "width": 128,
    "divider": {
      "x": 32
    },
    "stat_title": {
      "x": 28
    },
    "team": {
      "name": {
        "x": 1
      },
      "record": {
        "x": 59
      },
      "games_back": {
        "x": 124
      }
    }
  },
  "status": {
    "text": {
      "x": 56,
      "y": 46,
      "short_text": false
    },
    "scrolling_text": {
      "x": 0,
      "y": 58,
      "width": 128
    }
  },
  "teams": {
    "background": {
      "away": {
        "width": 128,
        "height": 16,
        "x": 0,
        "y": 0
      },
      "home": {
        "width": 128,
        "height": 16,
        "x": 0,
        "y": 16
      }
    },
    "name": {
      "away": {
        "x": 1,
        "y": 12
      },
      "home": {
        "x": 1,
        "y": 28
      }
    },
    "runs": {
      "away": {
        "x": 120,
        "y": 12
      },
      "home": {
        "x": 120,
        "y": 28
      }
    }
  }
}
```

### CODE REVIEW

**Comment by jasonbogovich** [comment]
img_3997
img_3998
img_3999

**Comment by ajbowler** [comment]
@jasonbogovich this is a little jacked, your changes aren't showing up in the diff at all.

**Comment by jasonbogovich** [comment]
I apologize, I don't have a lot of experience collaborating on github. Feel free to change anything or shove me in the right direction.

**Comment by ajbowler** [comment]
@jasonbogovich you'll need to fork this repo into your own copy. Then you can add your new w128h64.json.example file and commit/push those changes to your fork, then open a pull request into this repository.

If that's a little confusing it's no big deal, I can bring the changes in

**Comment by jasonbogovich** [comment]
I just used the web interface. I didn't push a change.

**Comment by ajbowler** [comment]
I'll get these changes pushed up on a branch into a separate pull request

**Comment by jasonbogovich** [comment]
thx

**Comment by jasonbogovich** [comment]
One last bit, as you can see the zero doesn't look line up with the 1 in the Indians Game. I still need to work on the font.  Maybe that's another issue?

**Pull request closed without merging**
