### PR TITLE
Add pregame weather

### PR DESCRIPTION
**Pull request by tracerrx**
Added pregame weather.  In config.json must add `"pregame_weather": true,` note that pregame weather appears to be entered manually when the booth crew shows up.  For tonight's yankees game the api populated around 3pm today for a 7:05 start.

### CODE REVIEW

**Comment by tracerrx** [comment]
Screen Shot 2022-04-26 at 3 14 40 PM
Screen Shot 2022-04-26 at 3 14 28 PM
Screen Shot 2022-04-26 at 3 14 16 PM

**Comment by twfarley** [comment]
That’s cool. I wonder if it makes sense to put it on the same line as the start time. Thoughts?

**Comment by WardBrian** [comment]
You could have the setting be like debug_day where it’s either False, “time”, or “starters”

**Comment by tracerrx** [comment]
> That’s cool. I wonder if it makes sense to put it on the same line as the start time. Thoughts?

I figured we would put the National Broadcast Station on the game time line in the future

**Comment by tracerrx** [comment]
Yankees game weather just changed to "Drizzle"... Cool... Nationals/Marlins weather also just changed, so someone is updating them.

**Comment by twfarley** [comment]
Do we get the name of the park where the game is played? If so, we should put this on the bottom line with the start time like this:

7:05PM - Yankee Stadium - 65F Drizzle

**Comment by tracerrx** [comment]
Look like "officialVenue" is an link to another api call... So its possible but would require an additional api call I believe.  @WardBrian can clarify.

**Comment by tracerrx** [comment]
Scratch that.. looks like it under both? Screen Shot 2022-04-26 at 7 04 15 PM Wonder what the difference is between venue and officialVenue?

**Review by ty-porter — APPROVED** [review]
Unclear why the diff didn't update before swapping branches, but this LGTM now

**Pull request merged**
